# Generated by Django 3.1.2 on 2020-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='top_bid',
            field=models.CharField(default=models.CharField(max_length=15), max_length=15),
        ),
    ]
