# Generated by Django 3.1.2 on 2020-11-06 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201104_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.CharField(default='11/5/2020', max_length=10),
        ),
    ]
