# Generated by Django 3.1.2 on 2020-11-06 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201105_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
