# Generated by Django 3.1.2 on 2020-11-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201105_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.CharField(default='11/<built-in method date of datetime.datetime object at 0x000001EE3D8A73F0>/2020', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.CharField(default='11/6/2020', max_length=10),
        ),
    ]
